export enum RegistrationStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CONTACTED = 'CONTACTED',
  ASSESSMENT_REQUIRED = 'ASSESSMENT_REQUIRED',
  ASSESSMENT_SCHEDULED = 'ASSESSMENT_SCHEDULED',
  APPROVED = 'APPROVED',
  WAITLISTED = 'WAITLISTED',
  REJECTED = 'REJECTED',
  ENROLLED = 'ENROLLED',
  WITHDRAWN = 'WITHDRAWN',
}